version: "2"
linters:
  default: all
  disable:
    - varnamelen
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          allow:
            - golang.org/x/crypto/*
    errcheck:
      check-type-assertions: true
      check-blank: true
    exhaustruct:
      exclude:
        - 'github.com/bytemare/secp256k1.Scalar'
        - 'github.com/bytemare/secp256k1.Element'
    funlen:
      lines: 120
    gocritic:
      enable-all: true
      disabled-checks:
        - commentedOutCode
        - unnamedResult
    gosec:
      excludes:
        - G115
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign
      ignored-numbers:
        - '2'
        - '16'
        - '63'
        - '64'
        - '0x0'
        - '0x1'
        - '0xfffffffefffffc2f'
        - '0xffffffffffffffff'
    nlreturn:
      block-size: 2
    prealloc:
      simple: false
      for-loops: true
  exclusions:
    rules:
      - path: scalar.go
        linters:
          - commentedOutCode
      - path: element.go
        linters:
          - wsl
      - path: mapping.go
        linters:
          - wsl
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/bytemare/secp256k1)
        - blank
        - dot
        - alias
      no-inline-comments: true
      no-prefix-comments: true
      custom-order: true
    goimports:
      local-prefixes:
        - github.com/bytemare/secp256k1
    golines:
      max-len: 200
output:
  sort-order:
    - file
run:
  tests: false