// SPDX-License-Identifier: MIT
//
// Copyright (C) 2020-2025 Daniel Bourdrez. All Rights Reserved.
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree or at
// https://spdx.org/licenses/MIT.html
//
// Code generated by addchain. DO NOT EDIT.

package scalar

// invert computes s = 1/x (mod p) and returns it.
// For some reason, addchain outputs something different than from the examples, using the receiver in the computation,
// which doesn't work if the receiver and the argument point to the same element. Dereferencing and thus using a local
// copy of the original does the trick.
func (s *scalar) Invert(x *scalar) *scalar {
	// Inversion computation is derived from the addition chain:
	//
	//	_10       = 2*1
	//	_11       = 1 + _10
	//	_101      = _10 + _11
	//	_111      = _10 + _101
	//	_1001     = _10 + _111
	//	_1011     = _10 + _1001
	//	_1101     = _10 + _1011
	//	_110100   = _1101 << 2
	//	_111111   = _1011 + _110100
	//	_1111110  = 2*_111111
	//	_1111111  = 1 + _1111110
	//	_11111110 = 2*_1111111
	//	_11111111 = 1 + _11111110
	//	i17       = _11111111 << 3
	//	i19       = i17 << 2
	//	i20       = 2*i19
	//	i21       = 2*i20
	//	i39       = (i21 << 7 + i20) << 9 + i21
	//	i73       = (i39 << 6 + i19) << 26 + i39
	//	x127      = (i73 << 4 + i17) << 60 + i73 + _1111111
	//	i154      = ((x127 << 5 + _1011) << 3 + _101) << 4
	//	i166      = ((_101 + i154) << 4 + _111) << 5 + _1101
	//	i181      = ((i166 << 2 + _11) << 5 + _111) << 6
	//	i193      = ((_1101 + i181) << 5 + _1011) << 4 + _1101
	//	i214      = ((i193 << 3 + 1) << 6 + _101) << 10
	//	i230      = ((_111 + i214) << 4 + _111) << 9 + _11111111
	//	i247      = ((i230 << 5 + _1001) << 6 + _1011) << 4
	//	i261      = ((_1101 + i247) << 5 + _11) << 6 + _1101
	//	i283      = ((i261 << 10 + _1101) << 4 + _1001) << 6
	//	return      (1 + i283) << 8 + _111111
	//
	// Operations: 253 squares 40 multiplies
	//
	// Generated by github.com/mmcloughlin/addchain v0.4.0.

	// Allocate Temporaries.
	var (
		t0  = newScalar()
		t1  = newScalar()
		t2  = newScalar()
		t3  = newScalar()
		t4  = newScalar()
		t5  = newScalar()
		t6  = newScalar()
		t7  = newScalar()
		t8  = newScalar()
		t9  = newScalar()
		t10 = newScalar()
		t11 = newScalar()
		t12 = newScalar()
	)

	// Step 1: s = x^0x2
	s.Square(x)

	// Step 2: t2 = x^0x3
	t2.Multiply(x, s)

	// Step 3: t6 = x^0x5
	t6.Multiply(s, t2)

	// Step 4: t5 = x^0x7
	t5.Multiply(s, t6)

	// Step 5: t0 = x^0x9
	t0.Multiply(s, t5)

	// Step 6: t3 = x^0xb
	t3.Multiply(s, t0)

	// Step 7: t1 = x^0xd
	t1.Multiply(s, t3)

	// Step 9: s = x^0x34
	s.Square(t1)
	for i := 1; i < 2; i++ {
		s.Square(s)
	}

	// Step 10: s = x^0x3f
	s.Multiply(t3, s)

	// Step 11: t4 = x^0x7e
	t4.Square(s)

	// Step 12: t7 = x^0x7f
	t7.Multiply(x, t4)

	// Step 13: t4 = x^0xfe
	t4.Square(t7)

	// Step 14: t4 = x^0xff
	t4.Multiply(x, t4)

	// Step 17: t9 = x^0x7f8
	t9.Square(t4)
	for s := 1; s < 3; s++ {
		t9.Square(t9)
	}

	// Step 19: t10 = x^0x1fe0
	t10.Square(t9)
	for s := 1; s < 2; s++ {
		t10.Square(t10)
	}

	// Step 20: t11 = x^0x3fc0
	t11.Square(t10)

	// Step 21: t8 = x^0x7f80
	t8.Square(t11)

	// Step 28: t12 = x^0x3fc000
	t12.Square(t8)
	for s := 1; s < 7; s++ {
		t12.Square(t12)
	}

	// Step 29: t11 = x^0x3fffc0
	t11.Multiply(t11, t12)

	// Step 38: t11 = x^0x7fff8000
	for s := 0; s < 9; s++ {
		t11.Square(t11)
	}

	// Step 39: t8 = x^0x7fffff80
	t8.Multiply(t8, t11)

	// Step 45: t11 = x^0x1fffffe000
	t11.Square(t8)
	for s := 1; s < 6; s++ {
		t11.Square(t11)
	}

	// Step 46: t10 = x^0x1fffffffe0
	t10.Multiply(t10, t11)

	// Step 72: t10 = x^0x7fffffff80000000
	for s := 0; s < 26; s++ {
		t10.Square(t10)
	}

	// Step 73: t8 = x^0x7fffffffffffff80
	t8.Multiply(t8, t10)

	// Step 77: t10 = x^0x7fffffffffffff800
	t10.Square(t8)
	for s := 1; s < 4; s++ {
		t10.Square(t10)
	}

	// Step 78: t9 = x^0x7fffffffffffffff8
	t9.Multiply(t9, t10)

	// Step 138: t9 = x^0x7fffffffffffffff8000000000000000
	for s := 0; s < 60; s++ {
		t9.Square(t9)
	}

	// Step 139: t8 = x^0x7fffffffffffffffffffffffffffff80
	t8.Multiply(t8, t9)

	// Step 140: t7 = x^0x7fffffffffffffffffffffffffffffff
	t7.Multiply(t7, t8)

	// Step 145: t7 = x^0xfffffffffffffffffffffffffffffffe0
	for s := 0; s < 5; s++ {
		t7.Square(t7)
	}

	// Step 146: t7 = x^0xfffffffffffffffffffffffffffffffeb
	t7.Multiply(t3, t7)

	// Step 149: t7 = x^0x7fffffffffffffffffffffffffffffff58
	for s := 0; s < 3; s++ {
		t7.Square(t7)
	}

	// Step 150: t7 = x^0x7fffffffffffffffffffffffffffffff5d
	t7.Multiply(t6, t7)

	// Step 154: t7 = x^0x7fffffffffffffffffffffffffffffff5d0
	for s := 0; s < 4; s++ {
		t7.Square(t7)
	}

	// Step 155: t7 = x^0x7fffffffffffffffffffffffffffffff5d5
	t7.Multiply(t6, t7)

	// Step 159: t7 = x^0x7fffffffffffffffffffffffffffffff5d50
	for s := 0; s < 4; s++ {
		t7.Square(t7)
	}

	// Step 160: t7 = x^0x7fffffffffffffffffffffffffffffff5d57
	t7.Multiply(t5, t7)

	// Step 165: t7 = x^0xfffffffffffffffffffffffffffffffebaae0
	for s := 0; s < 5; s++ {
		t7.Square(t7)
	}

	// Step 166: t7 = x^0xfffffffffffffffffffffffffffffffebaaed
	t7.Multiply(t1, t7)

	// Step 168: t7 = x^0x3fffffffffffffffffffffffffffffffaeabb4
	for s := 0; s < 2; s++ {
		t7.Square(t7)
	}

	// Step 169: t7 = x^0x3fffffffffffffffffffffffffffffffaeabb7
	t7.Multiply(t2, t7)

	// Step 174: t7 = x^0x7fffffffffffffffffffffffffffffff5d576e0
	for s := 0; s < 5; s++ {
		t7.Square(t7)
	}

	// Step 175: t7 = x^0x7fffffffffffffffffffffffffffffff5d576e7
	t7.Multiply(t5, t7)

	// Step 181: t7 = x^0x1fffffffffffffffffffffffffffffffd755db9c0
	for s := 0; s < 6; s++ {
		t7.Square(t7)
	}

	// Step 182: t7 = x^0x1fffffffffffffffffffffffffffffffd755db9cd
	t7.Multiply(t1, t7)

	// Step 187: t7 = x^0x3fffffffffffffffffffffffffffffffaeabb739a0
	for s := 0; s < 5; s++ {
		t7.Square(t7)
	}

	// Step 188: t7 = x^0x3fffffffffffffffffffffffffffffffaeabb739ab
	t7.Multiply(t3, t7)

	// Step 192: t7 = x^0x3fffffffffffffffffffffffffffffffaeabb739ab0
	for s := 0; s < 4; s++ {
		t7.Square(t7)
	}

	// Step 193: t7 = x^0x3fffffffffffffffffffffffffffffffaeabb739abd
	t7.Multiply(t1, t7)

	// Step 196: t7 = x^0x1fffffffffffffffffffffffffffffffd755db9cd5e8
	for s := 0; s < 3; s++ {
		t7.Square(t7)
	}

	// Step 197: t7 = x^0x1fffffffffffffffffffffffffffffffd755db9cd5e9
	t7.Multiply(x, t7)

	// Step 203: t7 = x^0x7fffffffffffffffffffffffffffffff5d576e7357a40
	for s := 0; s < 6; s++ {
		t7.Square(t7)
	}

	// Step 204: t6 = x^0x7fffffffffffffffffffffffffffffff5d576e7357a45
	t6.Multiply(t6, t7)

	// Step 214: t6 = x^0x1fffffffffffffffffffffffffffffffd755db9cd5e91400
	for s := 0; s < 10; s++ {
		t6.Square(t6)
	}

	// Step 215: t6 = x^0x1fffffffffffffffffffffffffffffffd755db9cd5e91407
	t6.Multiply(t5, t6)

	// Step 219: t6 = x^0x1fffffffffffffffffffffffffffffffd755db9cd5e914070
	for s := 0; s < 4; s++ {
		t6.Square(t6)
	}

	// Step 220: t5 = x^0x1fffffffffffffffffffffffffffffffd755db9cd5e914077
	t5.Multiply(t5, t6)

	// Step 229: t5 = x^0x3fffffffffffffffffffffffffffffffaeabb739abd2280ee00
	for s := 0; s < 9; s++ {
		t5.Square(t5)
	}

	// Step 230: t4 = x^0x3fffffffffffffffffffffffffffffffaeabb739abd2280eeff
	t4.Multiply(t4, t5)

	// Step 235: t4 = x^0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe0
	for s := 0; s < 5; s++ {
		t4.Square(t4)
	}

	// Step 236: t4 = x^0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe9
	t4.Multiply(t0, t4)

	// Step 242: t4 = x^0x1fffffffffffffffffffffffffffffffd755db9cd5e9140777fa40
	for s := 0; s < 6; s++ {
		t4.Square(t4)
	}

	// Step 243: t3 = x^0x1fffffffffffffffffffffffffffffffd755db9cd5e9140777fa4b
	t3.Multiply(t3, t4)

	// Step 247: t3 = x^0x1fffffffffffffffffffffffffffffffd755db9cd5e9140777fa4b0
	for s := 0; s < 4; s++ {
		t3.Square(t3)
	}

	// Step 248: t3 = x^0x1fffffffffffffffffffffffffffffffd755db9cd5e9140777fa4bd
	t3.Multiply(t1, t3)

	// Step 253: t3 = x^0x3fffffffffffffffffffffffffffffffaeabb739abd2280eeff497a0
	for s := 0; s < 5; s++ {
		t3.Square(t3)
	}

	// Step 254: t2 = x^0x3fffffffffffffffffffffffffffffffaeabb739abd2280eeff497a3
	t2.Multiply(t2, t3)

	// Step 260: t2 = x^0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8c0
	for s := 0; s < 6; s++ {
		t2.Square(t2)
	}

	// Step 261: t2 = x^0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd
	t2.Multiply(t1, t2)

	// Step 271: t2 = x^0x3fffffffffffffffffffffffffffffffaeabb739abd2280eeff497a33400
	for s := 0; s < 10; s++ {
		t2.Square(t2)
	}

	// Step 272: t1 = x^0x3fffffffffffffffffffffffffffffffaeabb739abd2280eeff497a3340d
	t1.Multiply(t1, t2)

	// Step 276: t1 = x^0x3fffffffffffffffffffffffffffffffaeabb739abd2280eeff497a3340d0
	for s := 0; s < 4; s++ {
		t1.Square(t1)
	}

	// Step 277: t0 = x^0x3fffffffffffffffffffffffffffffffaeabb739abd2280eeff497a3340d9
	t0.Multiply(t0, t1)

	// Step 283: t0 = x^0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd03640
	for s := 0; s < 6; s++ {
		t0.Square(t0)
	}

	// Step 284: t0 = x^0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd03641
	t0.Multiply(x, t0)

	// Step 292: t0 = x^0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364100
	for s := 0; s < 8; s++ {
		t0.Square(t0)
	}

	// Step 293: s = x^0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd036413f
	s.Multiply(s, t0)

	return s
}
