name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.24', '1.23', '1.22' ]
    uses: bytemare/workflows/.github/workflows/test-go.yml@c2070f71515f4d66d299e6f8eb2ffb4e5369ca3e
    with:
      command: cd .github && make test
      version: ${{ matrix.go }}
